version: "3.7"
services:

  envoy:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    networks:
      - envoymesh
    expose:
      - "90"
      - "8001"
    ports:
      - "8000:90"
      - "8001:8001"

  api1:
    build:
      context: .
      dockerfile: Dockerfile-api1
    networks:
      envoymesh:
        aliases:
          - api1
    expose:
      - "8080"

networks:
  envoymesh: {}
